services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-translator-backend
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./venv_xtts:/app/venv_xtts  # Mount XTTS models if they exist
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/uploads
      - RESULTS_FOLDER=/app/results
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: video-translator-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads:
  results:

networks:
  default:
    name: video-translator-network 