services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: video-translator-backend
    ports:
      - "5001:5001"
    volumes:
      - ../uploads:/app/uploads
      - ../results:/app/results
      - ../models:/app/models  # Mount pre-downloaded XTTS models
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/uploads
      - RESULTS_FOLDER=/app/results
      - COQUI_TOS_AGREED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for heavy TTS workloads (XTTS v2 etc)
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '8.0'
        reservations:
          memory: 4G
          cpus: '4.0'

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: video-translator-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads:
  results:

networks:
  default:
    name: video-translator-network 